security:
    encoders:
        ShopBundle\Entity\User: bcrypt
#            algorithm: bcrypt

    providers:
        db_provider:
            entity:
                class: ShopBundle:User
                property: name

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    firewalls:
        main:
            anonymous: ~
            form_login:
                login_path: login
                check_path: login
                target_path_parameter: admin
            logout: true
            provider: db_provider

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/admin, roles: ROLE_ADMIN }
