site:
    path: /
    defaults: { _controller: ShopBundle:Site:index}

create:
    path: /create
    defaults: { _controller: ShopBundle:Site:create}

view:
    path: /view
    defaults: { _controller: ShopBundle:Site:view}
    requirements:
        id: \d+

update:
    path: /update
    defaults: { _controller: ShopBundle:Site:update}
    requirements:
        id: \d+

delete:
    path: /delete
    defaults: { _controller: ShopBundle:Site:delete}
    requirements:
        id: \d+
index:
    path: /products
    defaults: { _controller: ShopBundle:Products:index}

index:
    path: /categories
    defaults: { _controller: ShopBundle:Categories:index}